package se.sogeti.jobapplications.beans;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToOne;
import se.unlogic.standardutils.dao.annotations.Table;

@Table(name = "summer_job_requirements")
public class ApplicationRequirement {
	
	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;
	
	@DAOManaged
	private String name;
	
	@DAOManaged
	private Boolean status;
	
	@DAOManaged(columnName="municipalityJobId")
	@OneToOne(keyField="id")
	private MunicipalityJob job;

}