package se.sogeti.jobapplications.beans;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToOne;
import se.unlogic.standardutils.dao.annotations.Table;

@Table(name = "summer_job_requirements")
public class ApplicationRequirement {
	
	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;
	
	@DAOManaged
	private String name;
	
	@DAOManaged
	private Boolean status;
	
//	@DAOManaged(columnName="municipalityJobId")
//	@OneToOne(keyField="id")
//	private MunicipalityJob job;
	
	@DAOManaged(columnName="municipalityJobId")
	@ManyToOne(remoteKeyField="id")
	private MunicipalityJob job;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public MunicipalityJob getJob() {
		return job;
	}

	public void setJob(MunicipalityJob job) {
		this.job = job;
	}

	@Override
	public String toString() {
		return name + "(id: " + id + ")";
	}
}