package se.sogeti.jobapplications.beans;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "summer_job_business_sector_requirements")
public class BusinessSectorApplicationRequirement {

	@DAOManaged(autoGenerated=true)
	@Key
	@XMLElement
	private Integer id;
	
	@DAOManaged
	@XMLElement
	private String name;
	
	@DAOManaged
	@XMLElement
	private Boolean status;
	
	@DAOManaged(columnName="businessSectorJobId")
	@ManyToOne(remoteKeyField="id")
	private BusinessSectorJob job;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public BusinessSectorJob getJob() {
		return job;
	}

	public void setJob(BusinessSectorJob job) {
		this.job = job;
	}

	@Override
	public String toString() {
		return name + "(id: " + id + ")";
	}
}
