package se.sogeti.jobapplications.beans;

import java.sql.Date;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "summer_job_business_sector_job")
public class BusinessSectorJob {

	
	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;
	
	@DAOManaged
	@XMLElement
	private Date created;
	
	@DAOManaged
	@XMLElement
	private Date updated;
	
	@DAOManaged
	@XMLElement
	private String managerFirstname;
	
	@DAOManaged
	@XMLElement
	private String managerLastname;
	
	@DAOManaged
	@XMLElement
	private String managerPhonenumber;
	
	@DAOManaged
	@XMLElement
	private String managerEmail;
	
	@DAOManaged
	@XMLElement
	private String streetAddress;
	
	@DAOManaged
	@XMLElement
	private String zipCode;
	
	@DAOManaged
	@XMLElement
	private String city;

	@DAOManaged
	@XMLElement
	private Date startDate;
	
	@DAOManaged
	@XMLElement
	private Date endDate;
	
	@DAOManaged
	@XMLElement
	private String workTitle;
	
	@DAOManaged
	@XMLElement
	private String workDescription;
	
	@DAOManaged
	@XMLElement
	private Integer numberOfWorkersNeeded;
	
	@DAOManaged
	@XMLElement
	private String requirementsFreeText;
	
	@DAOManaged
	@XMLElement
	private Boolean approvedWorkplace;
	
	@DAOManaged
	@XMLElement
	private String approvedByUser;
	
	@DAOManaged
	@XMLElement
	private Date approvedDate;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<BusinessSectorMentor> mentors;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<BusinessSectorJobApplication> workers;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<BusinessSectorApplicationRequirement> requirements;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<Person> matchedPersons;
	
	@Override
	public String toString() {
		return workTitle + "(id: " + id + ")";
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public String getManagerFirstname() {
		return managerFirstname;
	}

	public void setManagerFirstname(String managerFirstname) {
		this.managerFirstname = managerFirstname;
	}

	public String getManagerLastname() {
		return managerLastname;
	}

	public void setManagerLastname(String managerLastname) {
		this.managerLastname = managerLastname;
	}

	public String getManagerPhonenumber() {
		return managerPhonenumber;
	}

	public void setManagerPhonenumber(String managerPhonenumber) {
		this.managerPhonenumber = managerPhonenumber;
	}

	public String getManagerEmail() {
		return managerEmail;
	}

	public void setManagerEmail(String managerEmail) {
		this.managerEmail = managerEmail;
	}

	public String getStreetAddress() {
		return streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getWorkTitle() {
		return workTitle;
	}

	public void setWorkTitle(String workTitle) {
		this.workTitle = workTitle;
	}

	public String getWorkDescription() {
		return workDescription;
	}

	public void setWorkDescription(String workDescription) {
		this.workDescription = workDescription;
	}

	public Integer getNumberOfWorkersNeeded() {
		return numberOfWorkersNeeded;
	}

	public void setNumberOfWorkersNeeded(Integer numberOfWorkersNeeded) {
		this.numberOfWorkersNeeded = numberOfWorkersNeeded;
	}

	public String getRequirementsFreeText() {
		return requirementsFreeText;
	}

	public void setRequirementsFreeText(String requirementsFreeText) {
		this.requirementsFreeText = requirementsFreeText;
	}

	public Boolean getApprovedWorkplace() {
		return approvedWorkplace;
	}

	public void setApprovedWorkplace(Boolean approvedWorkplace) {
		this.approvedWorkplace = approvedWorkplace;
	}

	public String getApprovedByUser() {
		return approvedByUser;
	}

	public void setApprovedByUser(String approvedByUser) {
		this.approvedByUser = approvedByUser;
	}

	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	public List<BusinessSectorMentor> getMentors() {
		return mentors;
	}

	public void setMentors(List<BusinessSectorMentor> mentors) {
		this.mentors = mentors;
	}

	public List<BusinessSectorJobApplication> getWorkers() {
		return workers;
	}

	public void setWorkers(List<BusinessSectorJobApplication> workers) {
		this.workers = workers;
	}

	public List<BusinessSectorApplicationRequirement> getRequirements() {
		return requirements;
	}

	public void setRequirements(
			List<BusinessSectorApplicationRequirement> requirements) {
		this.requirements = requirements;
	}

	public List<Person> getMatchedPersons() {
		return matchedPersons;
	}

	public void setMatchedPersons(List<Person> matchedPersons) {
		this.matchedPersons = matchedPersons;
	}
}
