package se.sogeti.jobapplications.beans;

import java.sql.Date;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name="summer_job_business_sector_job_application")
public class BusinessSectorJobApplication {

	@DAOManaged(autoGenerated=true)
	@Key
	@XMLElement
	private Integer id;
	
	@DAOManaged
	@XMLElement
	private Integer businessSectorJobId;
	
	@DAOManaged(columnName="businessSectorJobId")
	@ManyToOne(remoteKeyField="id",autoGet=false,autoAdd=false,autoUpdate=false)
	private BusinessSectorJob businessSectorJob;
	
	private Integer personId;
	
	@DAOManaged(columnName="personId")
	@ManyToOne(remoteKeyField="id",autoGet=false,autoAdd=false,autoUpdate=false)
	private Person person;

	@DAOManaged
	@XMLElement
	private Integer ranking;
	
	@DAOManaged
	@XMLElement
	private boolean hasDriversLicense;
	
	@DAOManaged
	@XMLElement
	private String driversLicenseType;
	
	@DAOManaged
	@XMLElement
	private boolean hasAccessToVehicle;
	
	@DAOManaged
	@XMLElement
	private String personalLetter;
	
	@DAOManaged
	@XMLElement
	private String cvLocation;
	
	@DAOManaged
	@XMLElement
	private boolean approvedApplication;
	
	@DAOManaged
	@XMLElement
	private String approvedByUser;
	
	@DAOManaged
	@XMLElement
	private Date approvedDate;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBusinessSectorJobId() {
		return businessSectorJobId;
	}

	public void setBusinessSectorJobId(Integer businessSectorJobId) {
		this.businessSectorJobId = businessSectorJobId;
	}

	public BusinessSectorJob getBusinessSectorJob() {
		return businessSectorJob;
	}

	public void setBusinessSectorJob(BusinessSectorJob businessSectorJob) {
		this.businessSectorJob = businessSectorJob;
	}

	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Integer getRanking() {
		return ranking;
	}

	public void setRanking(Integer ranking) {
		this.ranking = ranking;
	}

	public boolean isHasDriversLicense() {
		return hasDriversLicense;
	}

	public void setHasDriversLicense(boolean hasDriversLicense) {
		this.hasDriversLicense = hasDriversLicense;
	}

	public String getDriversLicenseType() {
		return driversLicenseType;
	}

	public void setDriversLicenseType(String driversLicenseType) {
		this.driversLicenseType = driversLicenseType;
	}

	public boolean isHasAccessToVehicle() {
		return hasAccessToVehicle;
	}

	public void setHasAccessToVehicle(boolean hasAccessToVehicle) {
		this.hasAccessToVehicle = hasAccessToVehicle;
	}

	public String getPersonalLetter() {
		return personalLetter;
	}

	public void setPersonalLetter(String personalLetter) {
		this.personalLetter = personalLetter;
	}

	public String getCvLocation() {
		return cvLocation;
	}

	public void setCvLocation(String cvLocation) {
		this.cvLocation = cvLocation;
	}

	public boolean isApprovedApplication() {
		return approvedApplication;
	}

	public void setApprovedApplication(boolean approvedApplication) {
		this.approvedApplication = approvedApplication;
	}

	public String getApprovedByUser() {
		return approvedByUser;
	}

	public void setApprovedByUser(String approvedByUser) {
		this.approvedByUser = approvedByUser;
	}

	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	public Integer getPersonId() {
		return personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}
}
