package se.sogeti.jobapplications.beans;

import java.sql.Date;

import se.sogeti.jobapplications.interfaces.Requirements;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.xml.XMLElement;

@XMLElement
public abstract class Job implements Requirements{

	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;
	
	@DAOManaged
	@XMLElement
	private Date created;
	
	@DAOManaged
	@XMLElement
	private Date updated;

	@DAOManaged
	@XMLElement
	private String workTitle;
	
	@DAOManaged
	@XMLElement
	private String workDescription;
	
	@DAOManaged
	@XMLElement
	private Integer numberOfWorkersNeeded;
	
	@DAOManaged
	@XMLElement
	private Boolean approvedWorkplace;
	
	@DAOManaged
	@XMLElement
	private Date approvedDate;
	
	@DAOManaged
	@XMLElement
	private String approvedByUser;
	
	@DAOManaged
	@XMLElement
	private Boolean isOverEighteen;
	
	@DAOManaged
	@XMLElement
	private Boolean hasDriversLicense;
	
	@DAOManaged(columnName="driversLicenseType")
	@ManyToOne(remoteKeyField="id", autoGet = true, autoAdd = true, autoUpdate = true)
	private DriversLicenseType driversLicenseType;
	
	@DAOManaged
	@XMLElement
	private String freeTextRequirements;
	
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public String getWorkTitle() {
		return workTitle;
	}

	public void setWorkTitle(String workTitle) {
		this.workTitle = workTitle;
	}

	public String getWorkDescription() {
		return workDescription;
	}

	public void setWorkDescription(String workDescription) {
		this.workDescription = workDescription;
	}

	public Integer getNumberOfWorkersNeeded() {
		return numberOfWorkersNeeded;
	}

	public void setNumberOfWorkersNeeded(Integer numberOfWorkersNeeded) {
		this.numberOfWorkersNeeded = numberOfWorkersNeeded;
	}

	public Boolean getApprovedWorkplace() {
		return approvedWorkplace;
	}

	public void setApprovedWorkplace(Boolean approvedWorkplace) {
		this.approvedWorkplace = approvedWorkplace;
	}

	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	public String getApprovedByUser() {
		return approvedByUser;
	}

	public void setApprovedByUser(String approvedByUser) {
		this.approvedByUser = approvedByUser;
	}
	
	@Override
	public String toString() {
		return workTitle + "(id: " + id + ")";
	}

	public Boolean getIsOverEighteen() {
		return isOverEighteen;
	}

	public String getFreeTextRequirements() {
		return freeTextRequirements;
	}

	public void setFreeTextRequirements(String freeTextRequirements) {
		this.freeTextRequirements = freeTextRequirements;
	}

	public void setIsOverEighteen(Boolean isOverEighteen) {
		this.isOverEighteen = isOverEighteen;
	}

	public Boolean getHasDriversLicense() {
		return hasDriversLicense;
	}

	public void setHasDriversLicense(Boolean hasDriversLicense) {
		this.hasDriversLicense = hasDriversLicense;
	}

	public DriversLicenseType getDriversLicenseType() {
		return driversLicenseType;
	}

	public void setDriversLicenseType(DriversLicenseType driversLicenseType) {
		this.driversLicenseType = driversLicenseType;
	}
	
}
