package se.sogeti.jobapplications.beans;

import java.sql.Date;
import java.util.List;

import se.sogeti.jobapplications.beans.municipality.MunicipalityJob;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;


@XMLElement
public abstract class JobApplication{
	
	@DAOManaged(autoGenerated=true)
	@Key
	@XMLElement
	private Integer id;

	@DAOManaged
	@XMLElement
	private Integer ranking;
	
	@DAOManaged
	@XMLElement
	private boolean hasDriversLicense;
	
	@DAOManaged
	@XMLElement
	private String driversLicenseType;
	
	@DAOManaged
	@XMLElement
	private boolean hasAccessToVehicle;
	
	@DAOManaged
	@XMLElement
	private String personalLetter;
	
	@DAOManaged
	@XMLElement
	private String cvLocation;
	
	@DAOManaged
	@XMLElement
	private boolean approvedApplication;
	
	@DAOManaged
	@XMLElement
	private String approvedByUser;
	
	@DAOManaged
	@XMLElement
	private Date approvedDate;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public Integer getRanking() {
		return ranking;
	}

	public void setRanking(Integer ranking) {
		this.ranking = ranking;
	}

	public boolean isHasDriversLicense() {
		return hasDriversLicense;
	}

	public void setHasDriversLicense(boolean hasDriversLicense) {
		this.hasDriversLicense = hasDriversLicense;
	}

	public String getDriversLicenseType() {
		return driversLicenseType;
	}

	public void setDriversLicenseType(String driversLicenseType) {
		this.driversLicenseType = driversLicenseType;
	}

	public boolean isHasAccessToVehicle() {
		return hasAccessToVehicle;
	}

	public void setHasAccessToVehicle(boolean hasAccessToVehicle) {
		this.hasAccessToVehicle = hasAccessToVehicle;
	}

	public String getPersonalLetter() {
		return personalLetter;
	}

	public void setPersonalLetter(String personalLetter) {
		this.personalLetter = personalLetter;
	}

	public String getCvLocation() {
		return cvLocation;
	}

	public void setCvLocation(String cvLocation) {
		this.cvLocation = cvLocation;
	}

	public boolean isApprovedApplication() {
		return approvedApplication;
	}

	public void setApprovedApplication(boolean approvedApplication) {
		this.approvedApplication = approvedApplication;
	}

	public String getApprovedByUser() {
		return approvedByUser;
	}

	public void setApprovedByUser(String approvedByUser) {
		this.approvedByUser = approvedByUser;
	}

	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}
	
	
}
