package se.sogeti.jobapplications.beans;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "summer_job_mentors")
@XMLElement
public class Mentor {

	@DAOManaged(autoGenerated=true)
	@Key
	@XMLElement
	private Integer id;

//	@DAOManaged
//	@XMLElement
//	private Integer municipalityJobId;
	
	@DAOManaged(columnName="municipalityJobId")
	@ManyToOne
	private MunicipalityJob job;
	
	@DAOManaged
	@XMLElement
	private String firstname;
	
	@DAOManaged
	@XMLElement
	private String lastname;
	
	@DAOManaged
	@XMLElement
	private String email;
	
	@DAOManaged
	@XMLElement
	private String mobilePhone;
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	public Integer getMunicipalityJobId() {
//		return municipalityJobId;
//	}
//
//	public void setMunicipalityJobId(Integer municipalityJobId) {
//		this.municipalityJobId = municipalityJobId;
//	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Override
	public String toString() {
		return "Mentor (id: " + getId() + ")";
	}

	public MunicipalityJob getJob() {
		return job;
	}

	public void setJob(MunicipalityJob job) {
		this.job = job;
	}
}
