package se.sogeti.jobapplications.beans;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name="summer_job_municipality_job_application")
@XMLElement
public class MunicpalityJobApplication {
	
	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;
	
	@DAOManaged(columnName="municipalityJobId")
	@ManyToOne(remoteKeyField="id",autoGet=false,autoAdd=false,autoUpdate=false)
	MunicipalityJob municipalityJob;
	
	@DAOManaged
	private String firstName;
	
	@DAOManaged
	private String lastName;
	
	@DAOManaged
	private Integer ranking;
}
