package se.sogeti.jobapplications.beans;

import java.lang.annotation.Documented;
import java.sql.Date;
import java.util.List;
import java.util.Map;

import se.sogeti.periodsadmin.beans.Period;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.OneToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "summer_job_municipality_job")
@XMLElement
public class MunicipalityJob {
	
	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;

	@DAOManaged
	@XMLElement
	private Date created;
	
	@DAOManaged
	@XMLElement
	private Date updated;
	
	@DAOManaged
	@XMLElement
	private String organization;
	
	@DAOManaged
	@XMLElement
	private String location;
	
	//Address
	@DAOManaged
	@XMLElement
	private WorkplaceAddress address;
	
	@DAOManaged
	@XMLElement
	private Period period;
	
	//Work
	@DAOManaged
	@XMLElement
	private String workTitle;
	
	@DAOManaged
	@XMLElement
	private String workDescription;
	
//	@DAOManaged(columnName="managerId")
//	@XMLElement
//	@OneToOne(keyField="id")
	@DAOManaged
	@XMLElement
	@OneToOne(autoGet=true,autoAdd=true, autoUpdate=true)
	private Manager manager;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<Mentor> mentors;
	
	@DAOManaged
	@XMLElement
	private Integer numberOfWorkersNeeded;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<MunicpalityJobApplication> workers;
	
	@DAOManaged
	@XMLElement
	@OneToMany
	private List<ApplicationRequirement> requirements;
	
}
