package se.sogeti.jobapplications.beans;

import java.sql.Date;
import java.util.List;
import java.util.Map;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "summer_work_municipality_job")
@XMLElement
public class MunicipalityJob {
	
	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;

	@DAOManaged
	@XMLElement
	private Date created;
	
	@DAOManaged
	@XMLElement
	private Date updated;
	
	@DAOManaged
	@XMLElement
	private String organization;
	
	@DAOManaged
	@XMLElement
	private String location;
	
	//Address
	@DAOManaged
	@XMLElement
	private String streetAddress;
	
	@DAOManaged
	@XMLElement
	private String postalCode;
	
	@DAOManaged
	@XMLElement
	private String city;
	
	@DAOManaged
	@XMLElement
	private Date startDate;
	
	@DAOManaged
	@XMLElement
	private Date stopDate;
	
	//Work
	@DAOManaged
	@XMLElement
	private String workTitle;
	
	@DAOManaged
	@XMLElement
	private String workDescription;
	
	@DAOManaged
	@XMLElement
	private String managersFirstname;
	
	@DAOManaged
	@XMLElement
	private String managersLastname;
	
	@DAOManaged
	@XMLElement
	private String managersMobilePhone;
	
	@DAOManaged
	@XMLElement
	private String managersEmail;
	
	@DAOManaged
	@XMLElement
	private String supervisors;
	
	@DAOManaged
	@XMLElement
	private Integer numberOfworkersNeeded;
	
	@DAOManaged
	@XMLElement
	@OneToMany
	private List<MunicpalityJobApplication> workers;
	
	@DAOManaged
	@XMLElement
	@OneToMany
	private List<ApplicationRequirement> requirements;
	
}
