package se.sogeti.jobapplications.beans;

import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name="summer_job_municipality_job_application")
@XMLElement
public class MunicipalityJobApplication {
	
	@DAOManaged(autoGenerated=true)
	@Key
	@XMLElement
	private Integer id;

	
	@DAOManaged(columnName="municipalityJobId")
	@ManyToOne(remoteKeyField="id",autoGet=false,autoAdd=false,autoUpdate=false)
	private MunicipalityJob municipalityJob;
	
	@DAOManaged(columnName="personId")
	@ManyToOne(remoteKeyField="id",autoGet=false,autoAdd=false,autoUpdate=false)
	private Person person;

	@DAOManaged
	@XMLElement
	private Integer ranking;
	
	@DAOManaged
	@XMLElement
	private boolean hasDriversLicense;
	
	@DAOManaged
	@XMLElement
	private String driversLicenseType;
	
	@DAOManaged
	@XMLElement
	private boolean hasAccessToVehicle;
	
	@DAOManaged(columnName="prefered_area_1")
	@ManyToOne(remoteKeyField="id")
	private Area preferedArea1;
	
	@DAOManaged(columnName="prefered_area_2")
	@ManyToOne(remoteKeyField="id")
	private Area preferedArea2;
	
	@DAOManaged(columnName="prefered_area_3")
	@ManyToOne(remoteKeyField="id")
	private Area preferedArea3;
	
	@DAOManaged
	@XMLElement
	private String personalLetter;
	
	@DAOManaged
	@XMLElement
	private String cvLocation;
}
