package se.sogeti.jobapplications.beans;

import java.sql.Date;
import java.util.List;

import se.sogeti.periodsadmin.beans.Period;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "summer_job_municipality_job")
@XMLElement
public class MunicipalityJob {


	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;
	
	@DAOManaged
	@XMLElement
	private Date created;
	
	@DAOManaged
	@XMLElement
	private Date updated;
	
	@DAOManaged(columnName="workplaceId")
	@XMLElement
	@ManyToOne(autoGet=true,autoAdd=true, autoUpdate=true, remoteKeyField="id")
	private Workplace workplace;
	
	@DAOManaged(columnName="periodId")
	@XMLElement
	@ManyToOne(autoGet=true,autoAdd=true, autoUpdate=true, remoteKeyField="id")
	private Period period;
	
	@DAOManaged
	@XMLElement
	private String workTitle;
	
	@DAOManaged
	@XMLElement
	private String workDescription;
	
	// Område, t.ex Barnomsorg
	@DAOManaged(columnName="areaId")
	@XMLElement
	@ManyToOne(remoteKeyField = "id", autoAdd = false, autoGet = false, autoUpdate = false)
	private Area area;
	
	@DAOManaged
	@XMLElement
	private Integer numberOfWorkersNeeded;
	
	@DAOManaged
	@XMLElement
	private Boolean approvedWorkplace;
	
	@DAOManaged
	@XMLElement
	private Date approvedDate;
	
	@DAOManaged
	@XMLElement
	private String approvedByUser;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<Mentor> mentors;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<MunicipalityJobApplication> workers;
	
	@DAOManaged
	@XMLElement
	@OneToMany(autoGet=true,autoAdd=true, autoUpdate=true)
	private List<ApplicationRequirement> requirements;
	
	@DAOManaged
	@XMLElement
	private String requirementsFreeText;

	@Override
	public String toString() {
		return workTitle + "(id: " + id + ")";
	}
}
