package se.sogeti.jobapplications.beans;

import java.util.List;

import se.sogeti.jobapplications.beans.business.BusinessSectorJobApplication;
import se.sogeti.jobapplications.beans.municipality.MunicipalityJobApplication;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name="summer_job_person_applications")
@XMLElement
public class PersonApplications {
	
	@DAOManaged(autoGenerated=true)
	@Key
	private Integer id;
	
	@DAOManaged
	private String socialSecurityNumber;
	
	@DAOManaged
	@OneToMany(autoGet=false)
	private List<MunicipalityJobApplication> municipalityApplications;
	
	@DAOManaged
	@OneToMany(autoGet=false)
	private List<BusinessSectorJobApplication> businessApplications;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSocialSecurityNumber() {
		return socialSecurityNumber;
	}

	public void setSocialSecurityNumber(String socialSecurityNumber) {
		this.socialSecurityNumber = socialSecurityNumber;
	}

	public List<MunicipalityJobApplication> getMunicipalityApplications() {
		return municipalityApplications;
	}

	public void setMunicipalityApplications(List<MunicipalityJobApplication> municipalityApplications) {
		this.municipalityApplications = municipalityApplications;
	}

	public List<BusinessSectorJobApplication> getBusinessApplications() {
		return businessApplications;
	}

	public void setBusinessApplications(List<BusinessSectorJobApplication> businessApplications) {
		this.businessApplications = businessApplications;
	}

	@Override
	public String toString() {
		return "PersonApplications [id=" + id + ", socialSecurityNumber=" + socialSecurityNumber
				+ ", municipalityApplications=" + municipalityApplications + ", businessApplications="
				+ businessApplications + "]";
	}

}
