package se.sogeti.periodsadmin.beans;

import java.sql.Date;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OrderBy;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

/**
 * 
 * @author Petter Johansson
 *
 */

@Table(name = "periods")
@XMLElement
public class Period {
	
	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer id;

	@DAOManaged
	@WebPopulate(required=true,maxLength=255)
	@XMLElement
	private String name;

	@DAOManaged
	@WebPopulate(required=true)
	@XMLElement
	private Date startDate;
	
	@DAOManaged
	@WebPopulate(required=true)
	@XMLElement
	private Date endDate;
	
	@DAOManaged
	@OrderBy
	@XMLElement
	private Integer sortIndex;
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getName() {
		return name;
	}
	
	public void setStartDate(Date date) {
		this.startDate = date;
	}
	
	public Date getStartDate() {
		return startDate;
	}
	
	public void setEndDate(Date date) {
		this.endDate = date;
	}
	
	public Date getEndDate() {
		return endDate;
	}
	
	public void setSortIndex(Integer sortIndex) {
		this.sortIndex = sortIndex;
	}
	
	public Integer getSortIndex() {
		return sortIndex;
	}

	@Override
	public String toString() {
		return name + " (id: " + getId() + ")";
	}
}
